import prisma from '@/lib/prisma'

export interface Section {
  id: string
  title: string
  tag?: string
}

export function extractSectionsFromCompiledSource(
  compiledSource: string,
): Section[] {
  try {
    // Look for: const sections = [...] (generated by rehypeAddMDXExports)
    const sectionsMatch = compiledSource.match(
      /const sections = (\[[\s\S]*?\]);/,
    )

    if (!sectionsMatch) {
      return []
    }

    const sectionsCode = sectionsMatch[1]
    const sections = JSON.parse(sectionsCode) as Section[]

    return Array.isArray(sections) ? sections : []
  } catch (error) {
    console.warn('Failed to extract sections from compiled source:', error)
    return []
  }
}

export const getSectionsByCoursePath = async (
  courseSlug: string
): Promise<Record<string, Section[]>> => {
  const lessons = await prisma.lesson.findMany({
    where: {
      section: {
        course: { slug: courseSlug },
      },
    },
    select: {
      slug: true,
      serializedBody: true,
      section: {
        select: {
          slug: true,
        },
      },
    },
  })

  const sectionsMap: Record<string, Section[]> = {}

  for (const lesson of lessons) {
    const path = `/${lesson.section.slug}/${lesson.slug}`

    if (lesson.serializedBody) {
      const serialized = lesson.serializedBody as { compiledSource: string }

      if (serialized?.compiledSource) {
        const sections = extractSectionsFromCompiledSource(
          serialized.compiledSource,
        )
        sectionsMap[path] = sections
      } else {
        sectionsMap[path] = []
      }
    } else {
      sectionsMap[path] = []
    }
  }

  return sectionsMap
}
