import prisma from '@/lib/prisma'

export interface Section {
  id: string
  title: string
  tag?: string
}

function extractSectionsFromCompiledSource(compiledSource: string): Section[] {
  try {
    // Look for: const sections = [...] (generated by rehypeAddMDXExports)
    const sectionsMatch = compiledSource.match(
      /const sections = (\[[\s\S]*?\]);/,
    )

    if (!sectionsMatch) {
      return []
    }

    const sectionsCode = sectionsMatch[1]
    const sections = JSON.parse(sectionsCode) as Section[]

    return Array.isArray(sections) ? sections : []
  } catch (error) {
    console.warn('Failed to extract sections from compiled source:', error)
    return []
  }
}

export async function getSectionsByCoursePath(
  courseSlug: string,
): Promise<Record<string, Section[]>> {
  const lessons = await prisma.lesson.findMany({
    where: {
      section: {
        course: { slug: courseSlug },
      },
    },
    include: {
      section: true,
    },
  })

  const sectionsMap: Record<string, Section[]> = {}

  for (const lesson of lessons) {
    // Create the path that matches the URL structure
    const path = `/${lesson.section.slug}/${lesson.slug}`

    // Extract sections from the serialized content
    if (lesson.serializedBody) {
      const serialized = lesson.serializedBody as { compiledSource: string }

      if (serialized?.compiledSource) {
        const sections = extractSectionsFromCompiledSource(
          serialized.compiledSource,
        )
        sectionsMap[path] = sections
      } else {
        sectionsMap[path] = []
      }
    } else {
      sectionsMap[path] = []
    }
  }

  return sectionsMap
}

export async function getSectionsByLessonSlug(
  lessonSlug: string,
): Promise<Section[]> {
  const lesson = await prisma.lesson.findUnique({
    where: { slug: lessonSlug },
  })

  if (!lesson?.serializedBody) {
    return []
  }

  const serialized = lesson.serializedBody as { compiledSource: string }

  if (serialized?.compiledSource) {
    return extractSectionsFromCompiledSource(serialized.compiledSource)
  }

  return []
}
