/**
 * Rename existing Problem rows in place (old slug -> new slug + title) so a
 * title change does NOT orphan the row and strand user progress. The content
 * sync keys on slugify(title); without this, a renamed problem becomes a new
 * row while the old row (holding every user's ProblemProgress) is orphaned and
 * shown as a duplicate.
 *
 * This is DEFENSIVE and progress-preserving:
 *   - It only renames a row when the old slug exists AND the new slug does not,
 *     so it is idempotent and safe to re-run and safe if prod has drifted.
 *   - It updates slug + title + link on the SAME row, so the row id — and every
 *     ProblemProgress FK pointing at it — is preserved. Nothing is deleted, so
 *     the onDelete: Cascade chain is never triggered.
 *
 * IMPORTANT: the map is generated by position-alignment and CONFLATES true
 * renames with problem REPLACEMENTS. Review prisma/problem-rename-map.json and
 * delete any entry that is a replacement (different problem at that position —
 * see the `review`/`confidence` flags) BEFORE applying, or you will move a
 * user's completion onto an unrelated problem.
 *
 * Usage:
 *   tsx src/scripts/migrate-renamed-problems.ts            # DRY RUN (default)
 *   tsx src/scripts/migrate-renamed-problems.ts --apply    # execute
 *   tsx src/scripts/migrate-renamed-problems.ts --map <file>
 */
import prisma from '@/lib/prisma'
import fs from 'fs'
import path from 'path'

type Entry = {
  lesson: string
  oldTitle: string
  oldSlug: string
  newTitle: string
  newSlug: string
  confidence?: number
  review?: boolean
}

function arg(name: string, def?: string) {
  const i = process.argv.indexOf(`--${name}`)
  return i >= 0 ? process.argv[i + 1] : def
}

async function main() {
  const apply = process.argv.includes('--apply')
  const mapFile = arg('map', path.join('prisma', 'problem-rename-map.json'))!
  const map: Entry[] = JSON.parse(fs.readFileSync(mapFile, 'utf8'))

  const stillFlagged = map.filter((m) => m.review)
  if (stillFlagged.length > 0) {
    console.error(
      `\n❌ ${stillFlagged.length} entries are still flagged for review (review: true).`,
    )
    console.error(
      `   Review ${mapFile}: keep true renames, DELETE replacements, and remove the "review" flag`,
    )
    console.error(`   from the entries you have confirmed. Refusing to proceed.`)
    process.exit(1)
  }

  console.log(`${apply ? '🚀 APPLYING' : '🔎 DRY RUN'} — ${map.length} rename entries from ${mapFile}\n`)

  let renamed = 0, skippedMissing = 0, skippedExists = 0, errors = 0

  for (const e of map) {
    const existing = await prisma.problem.findUnique({ where: { slug: e.oldSlug }, select: { id: true, lessonId: true } })
    if (!existing) { skippedMissing++; continue } // already migrated, or prod never had it
    const target = await prisma.problem.findUnique({ where: { slug: e.newSlug }, select: { id: true } })
    if (target) { skippedExists++; continue } // new slug already present — sync will reconcile; don't merge

    const progress = await prisma.problemProgress.count({ where: { problemId: existing.id } })
    console.log(`  ${e.oldSlug}  ->  ${e.newSlug}   (${progress} progress rows preserved)`)

    if (apply) {
      try {
        // Only slug + title change here; the content sync (upsert on the new
        // slug) then updates link/question/answer/etc. on this same row.
        await prisma.problem.update({
          where: { slug: e.oldSlug },
          data: { slug: e.newSlug, title: e.newTitle },
        })
        renamed++
      } catch (err) {
        errors++
        console.error(`    ⚠️ failed: ${(err as Error).message}`)
      }
    } else {
      renamed++
    }
  }

  console.log(
    `\n${apply ? 'renamed' : 'would rename'}: ${renamed} | skipped (old slug absent): ${skippedMissing} | skipped (new slug already exists): ${skippedExists} | errors: ${errors}`,
  )
  if (!apply) console.log(`\nRe-run with --apply to execute.`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(async () => { await prisma.$disconnect() })
